version: '3.8'
services:
  # Postgres service for the indexer
  postgres:
    image: postgres:13
    container_name: lazy-indexer-postgres
    environment:
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: indexer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "indexer"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: lazy-indexer-redis
    command: --loglevel warning --maxmemory-policy noeviction
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  # Lazy Indexer service
  lazy-indexer:
    image: gabrieltemtsen/lazy-indexer # Update to point to the Lazy Indexer  image
    container_name: lazy-indexer
    environment:
      DATABASE_URL: postgresql://indexer:password@postgres:5432/indexer
      REDIS_URL: redis://redis:6379
      HUB_REST_URL: https://hub.pinata.cloud
      HUB_RPC: hub-grpc.pinata.cloud
      HUB_SSL: "true"
      WORKER_CONCURRENCY: 5
      LOG_LEVEL: debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  # Opencast service
  opencast:
    build: ./ # Update to point to the Opencast path
    container_name: opencast
    environment:
      DATABASE_URL: postgresql://indexer:password@postgres:5432/indexer
      FC_HUB_URL: localhost:2283
      FC_HUB_USE_TLS: "false"
      APP_FID: 1
      APP_MNENOMIC: ""
      NEXT_PUBLIC_FC_CLIENT_NAME: "Opencast"
      NEXT_PUBLIC_WALLETCONNECT_ID: "0fcda49e9f4acad4b84401373fbc5a4f"
      NEXT_PUBLIC_URL: "http://localhost:3000"
      INDEXER_API_URL: "http://localhost:3005"
    ports:
      - "3000:3000"
    depends_on:
      - lazy-indexer
    networks:
      - app-network

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: bridge
